### ISSUE TITLE
A possible missing file

### ISSUE THREAD

**Issue by lemoX6530** [singer-yang/Aberration-Aware-Depth-from-Focus#3]
Greetings, 
I'm attracted by your project and ideas, therefore I downloaded your codes and tried to run it. I  started off from the '0_warm_up.py' and received a FileNotFoundError that indicates the absence of a file: './ckpt/rf50mm/PSFNet480x640_ks11.pkl' within the folder. 

It seems that the required process of loading PSFNet is interrupted due to such an error, could it be possible that a file is missing? 

Thanks!

**Comment by singer-yang** [comment]
Hello lemoX6530,

Thanks for your interest. We have uploaded our pretrained model. You can also run 1_fit_psfnet.py to train a psfnet for your own lens.

Best,
Xinge
