### ISSUE TITLE
Missing datasets link, func render_sample_ray() and func render_compute_image()

### ISSUE THREAD

**Issue by LinYark** [singer-yang/Aberration-Aware-Depth-from-Focus#4]
Such a solid work, thank you very much for your work, which helped me get started in this field.
However, there seem to be the following missing:
1.datasets sample-link, 
2.func render_sample_ray(),
3.func render_compute_image()

**Comment by singer-yang** [comment]
Hello LinYark,

Thanks a lot for your interest. 

Rendering-related functions will be open-sourced when our other paper (Curriculum Learning for ab initio Deep Learned Refractive Optics) gets accepted. Missing these two functions will not prevent you from re-implementing algorithms in this paper (Aberration-Aware Depth-from-Focus).

For dataset, please check the updated readme file for details.

Hope you enjoy it!

Best,
Xinge
